<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Legacy: sobre-apunta a net8.0-windows aunque no usa nada de Windows. -->
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Demo.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Proyecto EXTERNO a la solución (no está en DemoLegacyApp.sln). -->
    <ProjectReference Include="..\..\ExternalContracts\Contracts.csproj" />
  </ItemGroup>

</Project>
