<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Demo.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo.Domain\Demo.Domain.csproj" />
    <ProjectReference Include="..\Demo.Persistence\Demo.Persistence.csproj" />
    <ProjectReference Include="..\Demo.Native\Demo.Native.csproj" />
  </ItemGroup>

</Project>
