<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Demo.Persistence</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo.Domain\Demo.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.EventLog" Version="8.0.0" />
  </ItemGroup>

</Project>
