<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Demo.Tools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo.DataAccess\Demo.DataAccess.csproj" />
  </ItemGroup>

</Project>
