<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <RootNamespace>Demo.Native</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo.Domain\Demo.Domain.csproj" />
  </ItemGroup>

</Project>
